name: Test

on: ["push", "pull_request"]

jobs:
  linting:
    name: Linting
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Initialise the npm cache
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: npm-${{ runner.os }}-node-12.x
          restore-keys: |
            npm-${{ runner.os }}-node-12.x

      - name: Install npm dependencies
        run: npm install

      - name: Run linter
        run: npm run lint

  testing:
    name: Running tests
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [12.x]
        experimental: [false]
        include:
          - os: ubuntu-latest
            node: 14.x
            experimental: true
          - os: windows-latest
            node: 12.x
            experimental: true
          - os: macos-latest
            node: 12.x
            experimental: true

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Get the npm cache directory
        id: npm-cache
        run: |
          echo "::set-output name=dir::$(npm config get cache)"

      - name: Initialise the npm cache
        uses: actions/cache@v1
        with:
          path: ${{ steps.npm-cache.outputs.dir }}
          key: npm-${{ runner.os }}-node-${{ matrix.node }}
          restore-keys: |
            npm-${{ runner.os }}-node-${{ matrix.node }}
            npm-${{ runner.os }}-node-

      - name: Install npm dependencies
        run: npm install

      - name: Run tests
        run: npm test
